- name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@v2
  with:
    projectBaseDir: .
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_SCANNER_OPTS: >
      -Dsonar.scm.forceReloadAll=true
      -Dsonar.projectVersion=${{ github.run_id }}
